### ISSUE TITLE
Provider not set or invalid

### ISSUE THREAD

**Issue by ponarunkumar** [b9lab/faucet-barebone#1]
fileName: "http://localhost:8000/web3.js"
lineNumber: 3139
message: "Provider not set or invalid"

While the web3 package is installed and verified, the http provider is not getting set as expected. Any alternatives?

**Comment by xavierlepretre** [comment]
Can you put your files in a repo to have a look?

**Comment by ponarunkumar** [comment]
Thanks @xavierlepretre for your quick response. Repo - https://github.com/ponarunkumar/faucet-test.git

**Comment by xavierlepretre** [comment]
You added the line `var web3=require('web3');`.
Remove this line.

**Comment by ponarunkumar** [comment]
Removed @xavierlepretre . And receiving the following reference error.  
ReferenceError: web3 is not defined

**Comment by xavierlepretre** [comment]
Notice how you wrote:

```javascript
typeof web3 !== undefined)
```
When in fact it should have been:

```javascript
typeof web3 !== 'undefined')
```
Notice the 2 `'`?

**Comment by ponarunkumar** [comment]
Thanks! I should have noticed that. Appreciate your help @xavierlepretre
